### ISSUE TITLE
I18N Self-review

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#38]
Short i18n review checklist is [here](https://w3c.github.io/i18n-drafts/techniques/shortchecklist). The relevant documents are:

- https://www.w3.org/TR/pub-manifest/
- https://www.w3.org/TR/audiobooks/

The second document is largely based on the first, and adds comparatively very little; these additions are all irrelevant in terms of internationalization.

Note, also, that the first document was originally developed under the name "Web Publication" in a separate repository, i.e., the earlier issues referred to are in the https://github.com/w3c/wpub repository.

## Self test

(Only the relevant "sub" forms below have been copied from [the i18n form](https://www.w3.org/International/techniques/developing-specs.en). Other entries in that form are non-applicable.)

1. [ ] If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),

   1. [x] <a class="self" href="#lang_basics_1">​</a>It should be possible to associate a language with any piece of natural language text that will be read by a user. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_decl">more</a>
   2. [x] <a class="self" href="#lang_basics_inline">​</a>Where possible, there should  be a way to label natural language changes in inline text. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_decl">more</a>
        
        **N/A (Not Applicable)** 
   1. [x] <a class="self" href="#lang_basics_meta">​</a>Consider whether it is useful to express the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">intended linguistic audience</a> of a resource, in addition to specifying the language used for <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing</a>. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_decl">more</a>

        See the [global publication language tag](https://www.w3.org/TR/pub-manifest/#manifest-default-language-and-dir)
   1. [x] <a class="self" href="#tp_lang_values">​</a>A language declaration that indicates the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing language</a> for a range of text must associate  a single language  value with a specific range of text. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">more</a>

        The language tag can be set both globally and on individual items
   2. [x] <a class="self" href="#lang_attribute_xml">​</a>Use the HTML <code class="kw" translate="no">lang</code> and XML <code class="kw" translate="no">xml:lang</code> language attributes where appropriate to identify the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing language</a>, rather than creating a new attribute or mechanism. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_attribute_xml">more</a>

        **N/A (Not Applicable)** (the mechanism is inherited from JSON-LD)
   3. [x] <a class="self" href="#metadata_lang_values">​</a>It should be possible to associate a metadata-type language declaration (which indicates the intended use of the resource rather than the language of a specific range of text)  with multiple language values. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">more</a>

        There is a separate (global and local) marker for the language used _in the manifest_, and another one for the _language of the publication_. The latter is a list with decreasing priority for possibly several languages.
        (At this moment, ie, 27.08.'19, this is not yet in the draft, but it will be; see the [relevant WG resolution](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-08-26-pwg#resolution2).) 
   4. [x] <a class="self" href="#metadata_not_lang">​</a>Attributes that express the language of external resources should not use the HTML <code class="kw" translate="no">lang</code> and XML <code class="kw" translate="no">xml:lang</code> language attributes, but should use a different attribute when they represent metadata (which indicates the intended use of the resource rather than the language of a specific range of text). <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">more</a>

        **N/A (Not Applicable)** (there is no mechanism to set the language of "external" resources; it is up to the individual resources, e.g., HTML files, to do that).

   5. [x] <a class="self" href="#lang_use_bcp47">​</a>Values for language declarations must use BCP 47. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_values">more</a>
   6. [x] <a class="self" href="#lang_bcp_not_rfc">​</a>Refer to BCP 47, not to RFC 5646. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_values">more</a>
   7. [x] <a class="self" href="#lang_values_valid">​</a>Be specific about what level of conformance you expect for language tags. The word "valid" has special meaning in BCP 47. Generally "well-formed" is a better choice.
   8. [x] <a class="self" href="#lang_matching_bcp">​</a>Reference BCP47 for language tag matching.

   9.  [x] <a class="self" href="#lang_whole_res">​</a>The specification should indicate how to define the default text-processing language for the resource as a whole. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_whole_res">more</a>

       See the [global publication language tag](https://www.w3.org/TR/pub-manifest/#manifest-default-language-and-dir).
   10. [x] <a class="self" href="#lang_inherit">​</a>Content within the resource should inherit the language of the text-processing declared at the resource level, unless it is specifically overridden.
   11. [x] <a class="self" href="#lang_tp_meta">​</a>Consider whether it is necessary to have separate declarations to indicate the text-processing language versus metadata about the expected use of the resource. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_tp_meta">more</a>

        **N/A (Not Applicable)** (only one language is provided)

   12. [x] <a class="self" href="#lang_mixing">​</a>If there is only one language declaration for a resource, and it has more than one language tag as a value, it must be possible to identify the default text-processing language for the resource. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_tp_meta">more</a>

       **N/A (Not Applicable)** (there is only one declaration per resource). 
    1.  [x] <a class="self" href="#lang_block_inherit">​</a>By default, blocks of content should inherit any text-processing language set for the resource as a whole.   <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_block_inherit">more</a>

        **N/A (Not Applicable)** (there is no concept of a "block of content").
    2.  [x] <a class="self" href="#lang_block_change">​</a>It should be possible to indicate a change in language for blocks of content where the language changes. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_block_change">more</a>

        **N/A (Not Applicable)** (there is no concept of a "block of content").

   13. [x] <a class="self" href="#lang_inline_spans">​</a>It should be possible to indicate language for spans of inline text where the language changes. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_inline_spans">more</a>

        **N/A (Not Applicable)** (JSON(-LD) operates with single texts only.)

   14. [x] <a class="self" href="#dir_paragraphs">​</a>It must be possible to indicate base direction for each individual paragraph-level item of natural language text that will be read by someone. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#dir_paragraphs">more</a>

        **N/A (Not Applicable)** (there is no concept of a "paragraph level text").

   15. [x] <a class="self" href="#dir_inline">​</a>It must be possible to indicate base direction changes for embedded runs of inline bidirectional text for all natural language text that will be read by someone. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#dir_inline">more</a>

        **N/A (Not Applicable)**: (JSON(-LD) operates with single texts only.)

    3.  [x] <a class="self" href="#dir_inline">​</a>Annotating right-to-left text must require the minimum amount of effort for people who work natively with right-to-left scripts. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#dir_reasonable">more</a>

        See the definition of [`inDirection`](https://www.w3.org/TR/pub-manifest/#manifest-default-language-and-dir).

   16. [x] <a class="self" href="#bidi_lang">​</a>Do not assume that direction can be determined from language information. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_lang">more</a>

   17. [x] <a class="self" href="#bidi_values">​</a>Values for the default base direction should include left-to-right, right-to-left, and auto. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_values">more</a>

   18. [ ] <a class="self" href="#bidi_strings_metadata">​</a>Provide metadata constructs that can be used to indicate the base direction of any natural language string. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>

        This can be done globally, but not locally. The issue has been discussed elsewhere (see, e.g., [RDF Literals and Base Directions](https://w3c.github.io/rdf-dir-literal/)); essentially, this specification is based on JSON-LD and cannot unilaterally add new JSON-LD level structures to the manifest. This means that, in this version, this feature cannot be provided. See the discussion in [#354](https://github.com/w3c/wpub/issues/354), as well as the [text in the specification](https://www.w3.org/TR/pub-manifest/#manifest-specific-language-and-dir) explaining the situation.

   19. [x] <a class="self" href="#bidi_strings_metadata">​</a>Specify that consumers of strings should use  heuristics, preferably based on the Unicode Standard first-strong algorithm, to detect the base direction of a string except where metadata is provided. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>

        See the [discussion in the specification](https://www.w3.org/TR/pub-manifest/#manifest-specific-language-and-dir).

   20. [x] <a class="self" href="#bidi_strings_default">​</a>Where possible, define a field to  indicate the default direction for all strings in a given resource or document. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>
   21. [x] <a class="self" href="#bidi_strings_metadata_and_default">​</a>Do NOT assume that a creating a document-level default without the ability to change direction for any string is sufficient. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>
   22. [x] <a class="self" href="#bidi_strings_script_tag">​</a>If metadata is not available due to legacy implementations and cannot otherwise be provided, specifications <em class="rfc2119" title="MAY">MAY</em> allow a base direction to be interpolated from available language metadata. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>

        **N/A (Not Applicable)**

   23. [x] <a class="self" href="#bidi_strings_paired_controls">​</a>Specifications <em class="rfc2119" title="MUST NOT">MUST NOT</em> require the production or use of paired bidi controls. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>

    
2.  [x] If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.

    **N/A (Not Applicable)**
    
3.  [x] If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.

    **N/A (Not Applicable)**

4.  [x] If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers
    
    **N/A (Not Applicable)**
　
5.  [x] If the spec (or its implementation) sorts text

    **N/A (Not Applicable)**

6.  [x] If the spec (or its implementation) captures user input

    **N/A (Not Applicable)**

7.  [x] If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries

    The two items that use dates  (`datePublished` and `dateModified`) are defined as [ISO8601](http://www.iso.org/iso/catalogue_detail?csnumber=40874) data (which should cover all the points below).

    1.  [x] <a class="self" href="#loc_time_preCE">​</a>When defining calendar and date systems, be sure to allow for dates prior to the common era, or at least define handling of dates outside the most common range.
    2.  [x] <a class="self" href="#loc_time_utc">​</a>When defining time or date data types, ensure that the time zone or relationship to UTC is always defined.
    3.  [x] <a class="self" href="#loc_time_floating">​</a>Provide a health warning for conversion of time or date data types that are "floating" to/from incremental types, referring as necessary to the <a href="https://www.w3.org/TR/timezone/"><cite>Time Zones</cite> WG Note</a>.  <a href="https://www.w3.org/TR/timezone/">more</a>
    4.  [x] <a class="self" href="#loc_time_leapsec">​</a>Allow for leap seconds in date and time data types.  <a href="https://w3c.github.io/bp-i18n-specdev/#loc_time_leapsec">more</a>
    5.  [x] <a class="self" href="#loc_time_consistency">​</a>Use consistent terminology when discussing date and time values. Use 'floating' time for time zone independent values.
    6.  [x] <a class="self" href="#loc_time_zone_offset">​</a>Keep separate the definition of time zone from time zone offset.
    7.  [x] <a class="self" href="#loc_time_zone_ids">​</a>Use IANA time zone IDs to identify time zones. Do not use offsets or LTO as a proxy for time zone.
    8.  [x] <a class="self" href="#loc_time_zone_field">​</a>Use a separate field to identify time zone.
    9.  [x] <a class="self" href="#loc_time_week">​</a>When defining rules for a "week", allow for culturally specific rules to be applied.  <a href="https://w3c.github.io/bp-i18n-specdev/#loc_time_week">more</a>
    10. [x] <a class="self" href="#loc_time_week_number">​</a>When defining rules for week number of year, allow for culturally specific rules to be applied.
    11. [x] <a class="self" href="#loc_time_13">​</a>When non-Gregorian calendars are permitted, note that the "month" field can go to 13 (undecimber).
    12. [x] If the spec (or its implementation) allows any character encoding other than UTF-8.

8.  [x] If the spec (or its implementation) defines markup.

    **N/A (Not Applicable)**

9.  [x] If the spec (or its implementation) deals with names, addresses, time & date formats, etc

    (Only names are relevant in the specification.)
    1. [x] <a class="self" href="#loc_names_given_family">​</a>Check whether you really need to store or access given name and family name separately.  <a href="https://www.w3.org/International/questions/qa-personal-names#singlefield">more</a>

        Only a single name field is used.
    2. [x] <a class="self" href="#loc_names_limits">​</a>Avoid placing limits on the length of names, or if you do, make allowance for long strings.  <a href="https://www.w3.org/International/questions/qa-personal-names#singlefield">more</a>
    3. [x] <a class="self" href="#loc_names_first_last">​</a>Try to avoid using the labels 'first name' and 'last name' in non-localized contexts.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>
    4. [ ] <a class="self" href="#loc_names_extra_fields">​</a>Consider whether it would make sense to have one or more extra fields, in addition to the full name field, where users can provide part(s) of their name that you need to use for a specific purpose.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

        **N/A (Not Applicable)** (The class used for a Person has been defined by schema.org, this specification just takes it over. [schema.org's Person](https://schema.org/Person) has a number of relevant term, and this WG does not want to touch that class' definition.
    5. [x] <a class="self" href="#loc_names_how_contact">​</a>Allow for users to be asked separately how they would like you be addressed when someone contacts them.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

        **N/A (Not Applicable)** (there is no interaction with the user in the creation of this field).
    6. [x] <a class="self" href="#loc_names_relevant_info">​</a>If parts of a person's name are captured separately, ensure that the separate items can capture all relevant information.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

        **N/A (Not Applicable)**

    7. [x] <a class="self" href="#loc_names_algorithms">​</a>Be careful about assumptions built into algorithms that pull out the parts of a name automatically.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

        **N/A (Not Applicable)**

    8. [x] <a class="self" href="#loc_names_initials">​</a>Don't assume that a single letter name is an initial.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

        **N/A (Not Applicable)**

    9. [x] <a class="self" href="#loc_names_famname_reqd">​</a>Don't require that people supply a family name.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>
    10. [x] <a class="self" href="#loc_names_punctuation">​</a>Don't forget to allow people to use punctuation such as hyphens, apostrophes, etc. in names.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>
    11. [x] <a class="self" href="#loc_names_uppercase">​</a>Don't require names to be entered all in upper case.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>
    12. [x] <a class="self" href="#loc_names_spaces">​</a>Allow the user to enter a name with spaces.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>
    13. [x] <a class="self" href="#loc_names_same_names">​</a>Don't assume that members of the same family will share the same family name.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>

        **N/A (Not Applicable)**

    14. [x] <a class="self" href="#loc_names_nee">​</a>It may be better for a form to ask for 'Previous name' rather than 'Maiden name' or 'née'.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>

        **N/A (Not Applicable)**

    15. [x] <a class="self" href="#loc_names_latin_native">​</a>You may want to store the name in both Latin and native scripts, in which case you probably need to ask the user to submit their name in both native script and Latin-only form, as separate items.  <a href="https://www.w3.org/International/questions/qa-personal-names#encoding">more</a>

        All "name" fields are defined as (possibly) *arrays* of names, and each item can have its language tag set.
 
10. [x] If the spec (or its implementation) describes a format or data that is likely to need localization.

    **N/A (Not Applicable)**

11. [x] If the spec (or its implementation) makes any reference to or relies on any cultural norms

    **N/A (Not Applicable)**

**Comment by iherman** [comment]
@aphillips,@r12a : comments?

**Comment by xfq** [comment]
The link to the Audiobook Profile seems broken?

**Comment by iherman** [comment]
Oops… sorry. I have changed the reference.

Thanks!

**Comment by xfq** [comment]
Thanks @iherman! (I fixed some other broken links I noticed while reading the self review.)

**Comment by iherman** [comment]
@xfq, most of the other links come from the original review form, I have just copy/pasted it. Maybe it is worth checking with @r12a to see where those updates should go...

**Comment by xfq** [comment]
@iherman I just fixed some links to the pub-manifest spec (there were typos in the URL).

**Comment by iherman** [comment]
@xfq the eagle-eye:-)

**Comment by r12a** [comment]
> Where possible, there should be a way to label natural language changes in inline text. more
> N/A (Not Applicable)

I think that this _is_ applicable (you may have a book title that is multilingual), but there is no way to achieve it other than using HTML markup, right?

**Comment by iherman** [comment]
Well... there is no such thing as inline text in the manifest, that is what misled me. But yes, it may be possible to imagine a multilingual book title, but that would indeed require HTML markup.

Although not exactly the same, but the book title's item is defined as a _sequence_ of literals, i.e., it is possible to add several titles. The main reason of having this is to allow for titles in different languages to co-exist in the manifest. That can be done without any problems.

**Comment by aphillips** [comment]
I have reviewed the open issues from the I18N horizontal review of this spec and all of them appear to have been addressed to our satisfaction. Thank you for your support.

Issues: https://github.com/w3c/i18n-activity/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Awpub

**Comment by iherman** [comment]
Thanks @aphillips
